# Generated by Django 5.2.6 on 2025-10-04 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='parent',
        ),
        migrations.AddField(
            model_name='adminorganization',
            name='hub',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='admin_organization', to='core.huborganization'),
            preserve_default=False,
        ),
    ]
