# Generated by Django 5.2.6 on 2025-10-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_organization_parent_adminorganization_hub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaboratororganization',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='huborganization',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='partnerorganization',
            name='organization',
        ),
        migrations.AddField(
            model_name='organization',
            name='name',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='role',
            field=models.CharField(choices=[('partner', 'Partner Organization'), ('admin', 'Admin Organization')], max_length=50),
        ),
        migrations.DeleteModel(
            name='AdminOrganization',
        ),
        migrations.DeleteModel(
            name='CollaboratorOrganization',
        ),
        migrations.DeleteModel(
            name='HubOrganization',
        ),
        migrations.DeleteModel(
            name='PartnerOrganization',
        ),
    ]
