# Generated by Django 5.2.6 on 2025-10-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('collaborator', 'Collaborator User'), ('manager', 'Manager User')], default='collaborator', max_length=50),
        ),
    ]
