# Generated by Django 5.2.6 on 2025-10-28 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_projectworkflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectworkflow',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project_workflows', to='core.organization'),
            preserve_default=False,
        ),
    ]
