# Generated by Django 5.2.6 on 2025-10-31 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_projectworkflow_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='project_stages', to='core.organization')),
                ('project_workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.projectworkflow')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('project_workflow', 'order')},
            },
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
    ]
