# Generated by Django 5.2.6 on 2025-10-31 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_projectstage_delete_stage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectstage',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_stages', to='core.organization'),
        ),
    ]
