# Generated by Django 5.2.6 on 2025-11-03 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_projectstage_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='finished_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='started_at',
        ),
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
