# Generated by Django 5.2.6 on 2025-11-06 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_customuser_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='organization',
        ),
        migrations.AddField(
            model_name='project',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.tenantorganization'),
            preserve_default=False,
        ),
    ]
