# Generated by Django 5.2.6 on 2025-11-06 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_project_organization_project_tenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectstage',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='projectworkflow',
            name='organization',
        ),
        migrations.AddField(
            model_name='projectstage',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_stages', to='core.tenantorganization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectworkflow',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project_workflows', to='core.tenantorganization'),
            preserve_default=False,
        ),
    ]
