# Generated by Django 5.2.6 on 2025-11-06 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_projectstage_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
