# Generated by Django 5.2.6 on 2025-11-06 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_partnerorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organization_type',
            field=models.CharField(choices=[('tenant', 'Tenant Organization'), ('partner', 'Partner Organization')], default='tenant', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.partnerorganization'),
        ),
    ]
