# Generated by Django 5.2.6 on 2025-11-06 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_customuser_organization_type_customuser_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='partner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.partnerorganization'),
            preserve_default=False,
        ),
    ]
