# Generated by Django 5.2.6 on 2025-11-11 13:10

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_project_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_cost_currency',
            field=models.CharField(choices=[('brl', 'BRL'), ('usd', 'USD')], default='brl', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_duration',
            field=models.DurationField(default=datetime.timedelta(days=30)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='innovationType',
            field=models.CharField(choices=[('product', 'Product'), ('service', 'Service'), ('business_process', 'Business Process'), ('model', 'Model')], default='product', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='problem_to_solve',
            field=models.CharField(default='example', max_length=255),
            preserve_default=False,
        ),
    ]
