# Generated by Django 5.2.6 on 2025-11-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_project_estimated_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='estimated_cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='estimated_cost_currency',
            new_name='cost_currency',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='estimated_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='problem_to_solve',
            new_name='problem',
        ),
        migrations.AddField(
            model_name='project',
            name='benefit',
            field=models.CharField(default='Example', max_length=255),
            preserve_default=False,
        ),
    ]
