# Generated by Django 5.2.6 on 2025-11-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_rename_estimated_cost_project_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='cost_currency',
        ),
        migrations.AlterField(
            model_name='project',
            name='benefit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='cost',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='problem',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
