# Generated by Django 5.2.6 on 2025-11-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_project_cost_currency_alter_project_benefit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='innovationType',
            new_name='innovation_type',
        ),
    ]
